### ISSUE TITLE
ND Receives Multiple New Member Welcome Letters with New Password

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#1]
Lisa Jo Landsburg has received multiple Welcome Letters to the GSRN Network.  She is the ND and she is not a GSRN member listed in SalesForce. 

Why would she be receiving welcome letters? This resets her password.  She should not get one at all because she is not a member (I checked the Roster, the Remove Member list in Network Admin, and SalesForce to make sure). 

We are concerned that members are also receiving multiple Welcome letters and their passwords are being reset.  We have not had anyone complain yet but want to get in front of this. 

<img width="437" alt="screen shot 2017-02-14 at 12 54 04 pm" src="https://cloud.githubusercontent.com/assets/25776549/22948650/9208ba18-f2bc-11e6-9eec-8fa0a66bed6a.png">

**Comment by beck24** [comment]
I *think* (not sure without digging into the code), that the ND is supposed to get a copy of the welcome emails.  I have a vague recollection of that being something that was requested so you could ensure they were going out correctly.  If that's the case, she should be getting a copy of the email when a new member joins.  It shouldn't be resetting her password though - are you sure it is doing that and not just being misinterpreted due to the email?

**Comment by beck24** [comment]
I've put in an additional check when the welcome email goes out so that it shouldn't get sent to the ND of the network.

**Comment by ncadjan** [comment]
Matt--Just checking:  The ND should receive a CC when the email goes out to a Member.  She shouldn't receive a Welcome letter for herself.  RIGHT?   I don't know quite how to test this one.

**Comment by beck24** [comment]
Yes - you can send/resend a welcome email to a member from the network admin page.  The ND will get a copy.

**Comment by ncadjan** [comment]
Ok.  The issue that we were concerned about is that the ND herself was receiving multiple emails to welcome HER (not the member) and she was getting her password reset.   Does that make sense?

**Comment by beck24** [comment]
Yeah that makes sense, that shouldn't be/isn't happening here, she is getting a copy of the email that is sent to the member.

**Comment by ncadjan** [comment]
But she WAS getting multiple ones so I guess we will wait and see if her password gets reset again and then we will deal with it.   Let's drop this for now and wait until it actually happens and she can let us look at what happened in the system.  No $$ left for a witch hunt.

**Comment by beck24** [comment]
oh yeah, that, I just put in a check to prevent sending that email to ND's while I was in there

**Comment by ncadjan** [comment]
So you need to fix something for us to test it? IT is the BCC person that is not getting it.

**Comment by beck24** [comment]
Sorry, I'm confused now.

ND should get a copy of the welcome email that is sent to the members.  ND should NOT get a welcome email for themselves.  The BCC email actually gets a CC (not a BCC) of the ND copy.

**Comment by ncadjan** [comment]
Yes


1.       ND receives a copy of the Welcome letter for each network member

2.       ND does NOT receive a Welcome letter for themselves (with a new password for them).


Yes, we noticed that the BCC was actually a CC and that is fine but it isn’t reaching the intended person.  We put my email, John’s email and Ari’s in to test it and none of us received the CC of the ND copy of the email.

Boy that was a tongue/finger twister.

**Comment by beck24** [comment]
It's working locally - here's the screenshots.  I resend the email to RButler (whose email I have set to mine in my copy).  I receive 2 copies of the email.  One is addressed to RButler (matt+rb@arckinteractive.com).  The other is addressed to Lisa Jo (matt+lisa@arckinteractive.com) with a cc to the plugin setting email (matt+cc@arckinteractive.com).

So they are definitely being sent.

One thing - we are no longer sending emails to someone who is already in another network, so make sure in your test you're not just adding an existing person to a new network and expecting an email.  It either needs to be a new account, or use the resend function.

![screen shot 2017-04-12 at 10 31 53 pm](https://cloud.githubusercontent.com/assets/738363/24991534/50944976-1fd0-11e7-812d-3068f69fc401.png)
![screen shot 2017-04-12 at 10 34 52 pm](https://cloud.githubusercontent.com/assets/738363/24991533/5085fb5a-1fd0-11e7-9af7-8e6db971d641.png)
