### ISSUE TITLE
Update Quick Tour Graphic to include IS and Hamburger Menu

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#18]
We need to add 2 additional screens to the Quick Tour for the Hamburger Menu and the Innovation Spotlight.

**Comment by ncadjan** [comment]
Hamburger Menu

<img width="385" alt="qt menu" src="https://cloud.githubusercontent.com/assets/25776549/23163129/805a0128-f7ee-11e6-9137-03a58b74ed89.png">

**Comment by ncadjan** [comment]
![engage is new logo](https://cloud.githubusercontent.com/assets/25776549/23163329/3a0b0996-f7ef-11e6-82ea-c4ac8ec0d39e.png)

**Comment by ncadjan** [comment]
<img width="549" alt="is sample" src="https://cloud.githubusercontent.com/assets/25776549/23163357/6158eebe-f7ef-11e6-9f7c-d2aa59dd125a.png">

**Comment by ncadjan** [comment]
<img width="388" alt="qt is with old comment" src="https://cloud.githubusercontent.com/assets/25776549/23163373/6de36ae2-f7ef-11e6-8dea-55e1b1eadbc7.png">

**Comment by ncadjan** [comment]
Innovation Spotlight 

<img width="388" alt="qt is" src="https://cloud.githubusercontent.com/assets/25776549/24265120/0b851a62-0fc8-11e7-9e1e-403204cd995d.png">

**Comment by ncadjan** [comment]
Innovation Spotlight QT Page uses this graphic 
![Uploading Innovation Spotlight QT Graphic.png…]()

**Comment by ncadjan** [comment]
Innovation Spotlight uses this graphic
![innovation spotlight qt graphic](https://cloud.githubusercontent.com/assets/25776549/24265186/44e5cd92-0fc8-11e7-8f4b-b8761ef8a33d.png)

**Comment by ncadjan** [comment]
I can send you two separate pieces for this IS graphic if you need them.

**Comment by beck24** [comment]
If you can send me the graphics how you want them I can put them into place

**Comment by ncadjan** [comment]
Last time you said you needed to create them so I added the elements in GitHub and a sample.  Do you want me to create the QT pages?  Do I just create the inner photo in white?  I suppose you create the wrapper with the Next Buttons?

Nancy Cadjan
Network Specialist
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[cid:image001.png@01D2A700.67D1FFA0]

**Comment by beck24** [comment]
actually don't worry about it - I got it I think - I'll post a screenshot when I'm done so you can verify it's what you want

**Comment by beck24** [comment]
Is there a specific order you want these in? Or just append them as page 7 and 8?

**Comment by ncadjan** [comment]
Good question. Do you think the menu works best first so they can see it? The leadership wants innovation spotlight to be up front. Does it seem ok second?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by beck24** [comment]
Yeah I can order them however you like, I'll do menu first, IS second, then everything else in the same order after

**Comment by ncadjan** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by beck24** [comment]
![screen shot 2017-03-27 at 1 20 28 pm](https://cloud.githubusercontent.com/assets/738363/24376788/fff15fee-12f1-11e7-8f10-e476e1deccde.png)
![screen shot 2017-03-27 at 1 33 16 pm](https://cloud.githubusercontent.com/assets/738363/24376789/fff1cbbe-12f1-11e7-9ef7-f20b93fdad07.png)

**Comment by ncadjan** [comment]
Matt, 

I can only access the two new pages and they are numbered 7/8 and 8/8.  I can't see 1-6 anymore. 

I will send you the MP4 of my experience in an email.   (I sent it oops from my personal email)

**Comment by ncadjan** [comment]
A few other things:
1. John says that swiping from 8 to 1 allows him to see the other pages but not the arrows--my experience.  But you can't swipe 7 back to 6
2. There is a typo on the Insights library page--it should be "lessons learned from our members" instead of out members. 


ALSO:  the Hamburger Menu and the Insights Library should be the first and second page of the QT.
