### ISSUE TITLE
Fix Notification Toggle ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#19]
Toggle Fix for Notifications (allow notifications/Settings/Main Menu Toggle Off then can’t toggle On)

See Basecamp: https://basecamp.com/1787386/projects/295667/messages/64875304

**Comment by beck24** [comment]
There's a bit of unknown here so I'm using 2 tags to give a range

**Comment by ncadjan** [comment]
Can we add a note just before Notification button? See Card #30

**Comment by beck24** [comment]
This is the last app-thing to address, I got #30 done and it's independent of whether we stick with pushwoosh or onesignal.  At this point it doesn't really matter to me, but let me know what's been decided so I can get it done :)

**Comment by ncadjan** [comment]
Ok.  I looked at the site but I know so little about notification systems that I don’t know how to judge it.  I understand that John is concerned because we invested time in PushWoosh and moving to another tool scares him because he is afraid other things will break.  What do you think?

**Comment by beck24** [comment]
I don't think there's much risk, but if that's the concern then let's just stick with what we have

**Comment by ncadjan** [comment]
Let me ping Karl.  I was waiting to hear back from John.  Can you work on another ticket for tonight?

**Comment by beck24** [comment]
yeah

**Comment by beck24** [comment]
ok, so now I'm going to go back to recommending OneSignal

[Pushwoosh.pdf](https://github.com/arckinteractive/en-issues/files/884312/Pushwoosh.pdf)

I need at least 2 tags to be able to do this, but the developer account that is set up only has an allowance for a single tag.  The next tier up is the marketing account which would work, but that costs 3 times as much.  I think this justifies the switch to OneSignal...

**Comment by ncadjan** [comment]
Matt-When we tested this, we found a behavior that we want to verify. 

When I do a fresh install and click Don't Allow, the toggle in ENgage does not over-ride the iOS settings when I select Receive Notifications. 

If I change and allow Notifications in the iOS settings, the toggle does works both to receive or not to receive notifications (as expected).  

Is this the expected behavior?
