### ISSUE TITLE
Member to Member Connection Changes (matt estimated 5 hrs)

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#21]
Member to Member Connection Needs:
1.	Track what topic a member wants a connection about (already doing this)
2.	Track who we connected them to (already doing this) 
3.	Track number of EN Resources sent (already doing this)
4.	Track number External Resources sent (already doing this) 
5.	Track External Connections sent (only doing the number) switch to names instead of a number
6.	Track the attempts to set up a call between both people (new)
7.	Track that a call is scheduled and the date (new)
8.	Track that a call occurred (new)
9.	Track that a member was used as a contact and the subject (new)
10.	Add notes field for each connection that is scrollable and unlimited.  Can this date be auto dated?  Not a days ago but the actual date. (yes - Matt)

Edit Profile Page
1.	Add a new button to the left with the Member Connection Information (moving what is on the current Edit Profile Page + new features)
2.	Add a new button between new Member Connection button and Activity History button then move all the Member Scheduling Info
a.	Completed MC
b.	Next MC
c.	Scheduled MC
d.	Outreach
e.	Number Attempts
f.	Contact Notes
g.	Survey Sent
h.	Survey Reminder Date
i.	Survey Received Date
j.	NMO Date

MIRG Current:
1 Field displaying: 
•	Date
•	Who entered the connection
•	Topic
•	Member Connected with
•	# EN Resources 
•	# External Resources
•	# External Connections

MIRG Needs:

1.	Cell or cells showing who member was connected with (can we link to their profile - yes) and which specific topic they were connected with along with dates of first contact, call set and call completed.  These must be separate for each contact/topic. 
2.	Delta between the dates when the first contact is made to the date when it the contact is completed. 
3.	Cell showing a member and who they were recommended to along with the topic and the dates so that we can see which members are being used as connections.

**Comment by ncadjan** [comment]
Matt: I think the only thing I'm concerned about is how to represent all this in MIRG, space is limited and you can't really cram all of that in there and have it be all that usable
 
Nancy: Agreed in theory. But we generally don't run reports will all the data--just a subset and this would be a subset that someone would choose.

**Comment by ncadjan** [comment]
![m2m try 2](https://cloud.githubusercontent.com/assets/25776549/23182631/7f99fbec-f836-11e6-8d12-ee88dc49217f.jpg)

**Comment by ncadjan** [comment]
![m2m try 2](https://cloud.githubusercontent.com/assets/25776549/24229308/716b95e8-0f3e-11e7-9578-923f0d23f38a.jpg)
![mirg m2m](https://cloud.githubusercontent.com/assets/25776549/24229316/7a5440ba-0f3e-11e7-917c-06b2c4e6c73b.jpg)

**Comment by beck24** [comment]
ok this is turning into a far more complicated thing than I originally thought... I've got the input UI done and the output on the profile page, trying to make sense of the requirements for the MIRG stuff here and it seems like we're running into the same problem as with the csv export thing - you're trying to fundamentally change the output structure of MIRG which isn't really working.

I'll push what I have to ensight-test so you can see the input UI and profile display but this might be another candidate for a custom export...

**Comment by ncadjan** [comment]
OK.  Thanks.  How are we doing time wise?  And how are you feeling?

**Comment by beck24** [comment]
We're at 16hrs, and I'm not 100% yet, but hopefully by tomorrow I'll be back to normal.  Thanks for asking!

**Comment by ncadjan** [comment]
Take it easy. Tomorrow isn't going to make or break us. If you are back 100% on Monday with kids back at school, that is great.  I get it.  My kids are out next week but they are older.

**Comment by ncadjan** [comment]
Oh and can you remind me how to get to test?

**Comment by beck24** [comment]
http://ensight-test.arckdev.com

**Comment by ncadjan** [comment]
Matt--It looks like we are on the way! It works now but I am sad to say I forgot a few things in my description (things I think my brain assumed). 

We need to be able to update the fields associated with this member connection so that we can track Call Status; Call Set; Call Completed as this is a process.   I can see two different ways we could do this:

1. Add an Edit to the Recommended Resources on the Profile Page
2. Make the the Member Connections a separate page like Profile Notes, Activity History and Profile History and just display all of the connections on this page so that any of them can be edited at any time.  

There are plusses and minuses to each but I think I prefer #2 because it lessens the clutter on the Profile Page.  Member Connections are not often entered at the same time as the rest of the Profile info.  

What do you think?  

Also, I can see what you are saying about changing MIRG.  Did we work through how to do it for the meetings?  My brain is fried.  We could leave that to next week when we both have a better brain.  It seems like the same solution would work for both cases since we are trying to display multiple attributes associated with one member in a table format that can be sorted in Excel. 

Maybe the solution is to display it as we do now in MIRG and then have a custom CSV that we can use for reporting.  Because there are two different uses for the data:  1) An overview of the member (Which is easily accomplished in the MIRG layout and what was we created this for) 2) Data retrieval for reports that are external to MIRG (which is something that our totally awesome development has pushed to the forefront). 

John and I envisioned something called MARG (Member Administration Report Generator) and maybe we can create that some time so it associates with activities instead of people.  You can sometime tell me if we can do that in the database with different logic in the MARG.  NOT today.  Just putting it out there. 

I am guessing that is a way longer comment that you expected . . .

**Comment by beck24** [comment]
ok this has been separated into it's own separate process with full CRUD operation and is up on dev

for MIRG stuff let's talk it out tomorrow.  For the networks we just decided to add in another custom csv report

**Comment by ncadjan** [comment]
Awesome!  A couple questions--see the graphic
<img width="930" alt="screen shot 2017-04-04 at 12 11 43 pm" src="https://cloud.githubusercontent.com/assets/25776549/24672111/f19be73a-1930-11e7-8573-620e9770086d.png">

**Comment by beck24** [comment]
It's a typo, should have been the date.  Accepted/declined wasn't in your mockup.  I'll add it in.

**Comment by ncadjan** [comment]
OOPs.  Sorry for my mistake.

**Comment by beck24** [comment]
Moving this to the "in review column" as it includes the new page for the connect listings, the new inputs, new profile section, new MIRG csv view.

There's a lot here, so if we need a custom report let's make that it's own ticket so discussions on that don't get lost in the fray.

**Comment by ncadjan** [comment]
OK.

**Comment by ncadjan** [comment]
Matt,  The Resources For section that displays on the Member Profile pulls in my name because I created the connection.  It should display the member that the member 
was a resource for right? 
<img width="966" alt="screen shot 2017-04-10 at 4 42 39 pm" src="https://cloud.githubusercontent.com/assets/25776549/24885679/18d00044-1e0d-11e7-8686-3dedd08fc0f0.png">

**Comment by ncadjan** [comment]
Matt, did we decide not to include the Resource For data in the MIRG?  When you are looking at this bug above, maybe you can let me know if that is easy or time-consuming.

**Comment by ncadjan** [comment]
If the crew asks for it later, we will include the Resource For data in another round.
