### ISSUE TITLE
Change MIRG Report for Network Meeting Attendance

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#24]
Can we change the MIRG so that it displays the meeting names and the status in the MIRG report instead of just numbers beside the status?  I know this might be a brain bender because there are different meetings per network but what we want to know is did they attend a Spring meeting and did they attend a Fall Meeting.  Let's talk.

**Comment by beck24** [comment]
The numbers are already clickable to show which meetings are listed in each count.

If you still need it in the report itself I'm sure that can be done: I'm adding estimates via labels

**Comment by ncadjan** [comment]
We need to be able to see which meetings.  The clickable thing doesn't work for us because instead of having the meeting names in the report, it just gives a number.  The way we want to report has changed so having the meeting attendance status appear in separate columns for each of the meetings in an 18-month period will help us.

**Comment by ncadjan** [comment]
OK.  We have more info 

This is what we need: a new report called Network Meeting 

**Report Type:** Network Meetings 
**Select Filter:** All Participants  (this would be new and would include all member, all past members, and all guests) 
Network Meeting Participation (change the current way it displays to show the meetings and their status individually so that in the export they all appear--An example is below) 
Name  	 	Network	         Meeting		           Status	
Bob Smith	GTRN		2016 Spring GTRN	   Attended
Bob Smith	GTRN		2016 Spring HRRG	    RSVP-No
Bob Smith	GTRN		2017 Autumn GTRN   Attended 
Tom Jones	Guest		2016 Spring GTRN    Attended 

So we have Name, Network (we will have to add Guest or leave this blank to indicate Guest), Put the names of the networks and then the attendance.

**Comment by beck24** [comment]
I feel like something changed about this one since we talked but I can't find my notes.  I know there were issues with the query by network meeting in that the network participation isn't searchable in solr currently and the output can't be structured with Bob Smith listed on 3 different lines.  Do you remember what we decided?

**Comment by ncadjan** [comment]
It did change.  The last comments were based on our discussion but you wanted to do some research.  Here is the issue:  We need each entry to be its own line so that it can be pulled into Excel.  

We discussed having a report called Network Meeting that pulled all network attendance data for the past 18 months and displayed it per member. If this isn't possible, can we think of another way?  Currently, Tricia downloads the Export Meeting data for every meeting for the past 18 months, sorts the data and then moves it all in to a spreadsheet that she then combines all the meeting attendance for each member.  

She also needs to see the meeting attendance for each member individually.  Currently, you can see it in a MIRG report online but you cannot export it so she still has to download the data as described above and then sort it per person (in addition to per meeting). 

If we need to talk this one out, we could do it later tonight or tomorrow.  I am heading out to dance.

**Comment by beck24** [comment]
ok, lets revisit this one tomorrow if you're around

**Comment by ncadjan** [comment]
I am around except from 12pm on.  I have meetings then.

Nancy Cadjan
Network Specialist
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[cid:image001.png@01D2A720.B16A6E20]

**Comment by beck24** [comment]
ok, I'm available anytime after 9am

**Comment by ncadjan** [comment]
Matt--after talking with Tricia, we decided that it would be best to do two things: 

1. Change the MIRG report so that instead listing a number for attended, RSVP-No etc, that the field associated with the member listed all the meetings and the status the way you explained it could be done.  (See graphic below)

2. Create a special CSV file just for Tricia's needs.  I will create a different ticket for this. 

<img width="878" alt="screen shot 2017-03-28 at 10 51 55 am" src="https://cloud.githubusercontent.com/assets/25776549/24417438/a74b7a28-13a5-11e7-8a29-e8ded71935a9.png">

**Comment by ncadjan** [comment]
Looks good!  Thanks.
