### ISSUE TITLE
Add message before System Notifications ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#30]
When I installed GoTo Meeting on my phone, there was a message that appeared before the system Enable Notifications window that said "Never be late to another Meeting with a 5 minute reminder--Accept Notifications?"

If we can do that before the System Enable Notification, we give people a reason to click Allow. 

Maybe something like:  Get notified about innovative ideas from members and experts--Accept Notifications

**Comment by ncadjan** [comment]
FIRST MESSAGE THAT APPEARS before NOTIFICATIONS 
![file](https://cloud.githubusercontent.com/assets/25776549/24228573/c0e32aae-0f3a-11e7-83a5-138850483843.png)


THEN SYSTEM NOTIFICATION
![file1](https://cloud.githubusercontent.com/assets/25776549/24228572/be10ea6e-0f3a-11e7-9d4a-fcd141e95e46.png)

**Comment by beck24** [comment]
So I may have misunderstood this when we were talking last week - the Old Navy popup in the first pic is the ios default popup, and is the same as what is currently on the ENgage app.  It only happens the first time you attempt to register for notifications with an app.

The second picture is the only custom element here - what makes that pop-up?  I can't seem to get that app in Canada so I can't try it myself.  If it's just a case of creating a new popup for it I can do that, just need to know where/when it should present.  As far as I can find there's no way to *replace* the first initial one on ios which is what I thought was being asked.

**Comment by ncadjan** [comment]
So, the second picture is actually the first popup.  It comes before the System notification.  It would be launched directly after login and before notifications requests. Does that make sense?  Sorry GitHub took the photos in a different order than I had hoped.

Nancy Cadjan
Network Specialist
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[cid:image001.png@01D2A700.3A28D9C0]

**Comment by ncadjan** [comment]
I updated the order above.  Didn't know I could do that.

**Comment by ncadjan** [comment]
I just instated expensify and got the a notification before the system notifications. Sending it to you in email. I can't figure out how to attach to github on my phone while at my sons  guitar lesson

**Comment by beck24** [comment]
ok, I should be able to do something like that - shouldn't take long - an hour or so - say 2 with testing and stuff

**Comment by ncadjan** [comment]
Great!

**Comment by beck24** [comment]
![img_0039](https://cloud.githubusercontent.com/assets/738363/24381366/e2d04b7e-1304-11e7-8f4b-343580648e12.PNG)
![img_0040](https://cloud.githubusercontent.com/assets/738363/24381365/e2cdbc56-1304-11e7-931f-fe79a13c189b.PNG)

**Comment by ncadjan** [comment]
Awesome!

**Comment by ncadjan** [comment]
Can you change the text to say " Get notified about innovative ideas from members and experts!  Make sure to accept Notifications."

The dash by itself looks weird. And it looks more like a question and we want it to be a statement.

**Comment by beck24** [comment]
![img_0041](https://cloud.githubusercontent.com/assets/738363/24382451/371c17de-130b-11e7-89d7-fb2adcf8340a.PNG)
![img_0042](https://cloud.githubusercontent.com/assets/738363/24382452/37428efa-130b-11e7-9e5e-7dee7f5d9174.PNG)

**Comment by ncadjan** [comment]
Perfect!
