### ISSUE TITLE
Custom CSV

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#35]
This is the information that Tricia needs.

**Comment by ncadjan** [comment]
[Mockup.xlsx](https://github.com/arckinteractive/en-issues/files/904352/Mockup.xlsx)

**Comment by ncadjan** [comment]
This doesn't include how we want to do the M2M connections.  I don't know if this can be in the same report or if it has to be a separate .CSV

**Comment by beck24** [comment]
Looking at this now - I may be mis-remembering but I thought the csv export was for event membership.  The reason it couldn't work in MIRG was because they wanted the user to have a separate row for each event, but I don't see any event identifier or anything in this mockup.  Am I remembering wrong or what?

**Comment by ncadjan** [comment]
Let me get home and I'll look. I added a xls to the ticket on member reporting.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ncadjan** [comment]
Matt, we need the attached fields, some of them being the Member 2 Member connections.  When I had originally worked on this with Tricia, we thought it could all go into the one CSV file.  But, I think you are telling me that we need two.  Yes? Can we talk for 5 mins?

**Comment by ncadjan** [comment]
OK.  Let me clarify again in my head: 
1> The attached is the information Tricia needs.
2> We originally thought M2M could be pulled into this report. Seems like we can't get it into this report. 
3> Can we make make the report attached for everything except M2M and then make a separate CSV for that data with as close as possible same structure as this file (same Member Info columns such as First Name, Last Name, Network, End Date, etc)

**Comment by beck24** [comment]
I'm available for the next 4 hours if you want to chat.  I've paused work pending Paul getting an hours update.

**Comment by ncadjan** [comment]
In the M2M CSV, is it possible to list First Name Last Name instead of "For"?  This is how Tricia's reports are sorted.

**Comment by ncadjan** [comment]
Member 2 Member CSV is missing the Completed Dates. 
<img width="552" alt="screen shot 2017-04-12 at 2 15 00 pm" src="https://cloud.githubusercontent.com/assets/25776549/24977911/055650d8-1f8c-11e7-8a3c-790f8d587303.png">

**Comment by ncadjan** [comment]
BTW:  The Event report takes 30 minutes to load.  Lots of data.  I sent it to Tricia to review.

**Comment by beck24** [comment]
Yeah that's why I put that note on there that it could take a while.  It's essentially churning through a good chunk of the database to get all the information.  It's a big one.
