### ISSUE TITLE
Ask the Expert Added Functionality to ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#38]
We need to add a list of experts that members can connect with through their Network Director.  Here is what I would like to see: 
1. Create a new role type in ENsight for Expert.  This role should have the same access rights as the current Reference Role. (Alternatively, we could add a check box to Reference Role people to Display as Expert).  QUESTION: Can we make the expert network-specific?  This isn't a current request but I see it may come in the future so I want to know what this would take. 
2. Create a link in ENgage menu that goes to a page where the Experts are listed.  
3. Allow members to click the name of the expert, see their bio and then click on a Request a Connection button to launch an email to the Network Director. 
4. Populate the Request a Connection email with standard request text (we can work on this). 
5. Use the current Member Connections function to report on connections made. Question: Can we add a way to note that the connection is with an expert. 

Depending on cost for this, we can fall back to the same PDF strategy we are using for the Innovation Spotlight.

**Comment by beck24** [comment]
Roles as they exist are global in nature.  If you even think there's a possibility that you'll want/need it to be specific to certain networks that would change the underlying data model.  It can be done either way, but just giving you a heads up that if we go the roles route then your mind changes it will be much more difficult to switch.  One of those things that is best to get right the first time.

For 3: their bio is the existing profile view that already exists in the app? or something new?

5: not sure what you mean about the current member connections function - is that on the app or ensight?

Here's what I know so far:

Menu link, new page with list of users - custom list view: 4h

New role: 2hrs
Network-specific option - 4hrs

If it's network specific, on the app does the user only see experts from their networks?

Will need at least one new api endpoint for listing experts - 2hr

Do we need to know what they are an expert of?  If I'm looking for an expert in economics it might not be helpful to see a list of 100 experts, but their expertise ranges from agriculture to zoology - how would I narrow down to find the economics expert?

**Comment by ncadjan** [comment]
Excellent Questions.

Let's scrap making them specific to a network.  It was something I wondered about.
We can add a bio to a member or reference role in ENsight. I think that is accessed in ENgage in the Info button right?  It doesn't show by default.  Could we make a different interface for Reference roles so that it did show? 

I gave Karl an estimate of between 12-20 hours as it stands now.  Fair?

**Comment by beck24** [comment]
Yeah I think thats fair, if it ends up looking like more as we flush things out we can revise.

I'm not sure what you mean about the info button - should we jump on a call?

**Comment by ncadjan** [comment]
Duh.  If I scroll down, the Bio is right there.

How hard would it be to display only bios for the Reference/Expert Roles on the Experts’ profiles in ENgage?  We don’t want the members to have any contact information because we are brokering the contact.  We just need the bio.

**Comment by ncadjan** [comment]
I am actually not working today--just trying to do this on the fly so Karl can present at the meeting.  I think there is enough here.

**Comment by beck24** [comment]
When we built ENgage one of the things we discussed was whether roles were going to be a factor and that wasn't the case.  So ENgage has no idea who is a reference or expert or anything.  I can add in a simple role name and try to just change some things around dynamically.  You'd need to go through the profile and tell me what should be displayed for who.  That shouldn't be difficult, say an hour for adding some role information to the user export array, and another one or two for selective elements.

So, 3 hrs for role-based information

**Comment by ncadjan** [comment]
Thanks.

**Comment by ncadjan** [comment]
Matt--I took some time to design what an Expert Profile might look like 
![engage expert profile](https://user-images.githubusercontent.com/25776549/29123144-0139a0e2-7cd2-11e7-9920-d80f8f08a918.png)

**Comment by beck24** [comment]
This is ready for review - available on play store for beta testers and testflight for ios

The server-side stuff has been pushed to prod already.  There is an 'Expert' role that can be assigned.  Those are the people that will show up on the app.

**Comment by ncadjan** [comment]
Thanks Matt.  I looked at it in TestFlight and added 2 users.  Looks good.  I will play with it and have a meeting with Karl hopefully tomorrow and we can take a look.  What are the hours we are at now?

**Comment by beck24** [comment]
We're currently at 22.5hrs
