### ISSUE TITLE
Sync Issue Fix

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#39]
Karl would like to go ahead with the sync issue fix you suggest so that we can know when it fails.  Can you give me an estimate for this? 

https://basecamp.com/1787386/projects/295667/messages/70959245#comment_547363804

**Comment by beck24** [comment]
that's minor - less than an hour

**Comment by beck24** [comment]
and to answer the unanswered question there - yes someone would get an email every day when the sync has completed

**Comment by ncadjan** [comment]
Perfect.  I will get an email from Sang where he thinks they should be sent.

**Comment by ncadjan** [comment]
Email for this message:   entech@executivenetworks.com

**Comment by beck24** [comment]
Done
