### ISSUE TITLE
New Members not being added to ENask Automatically

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#41]
Matt, 

It seems that members if IRN-PM and IRN-HCA don't automatically access to ENAsk.  

Here are two new members in IRN-HCA:
1. Christina Burgwald did get access (she is also a member of OCEAN):  http://ensight.executivenetworks.com/profile/CBurgwald

2. Hector Chanin did not get access:  http://ensight.executivenetworks.com/profile/HChahin 

Could there be a setting on the IRN networks?

**Comment by beck24** [comment]
I don't see IRN-HCA listed in the permissions list for EN Ask

The way it's set up is that access is determined by network membership, where you have chosen to include and exclude certain networks.  Therefore networks need to be added to the list if they are to be included:

http://ensight.executivenetworks.com/forum/edit/2330672

Can you test after adding the required networks to the permissions list?

**Comment by ncadjan** [comment]
Yes, thanks. I can do that.
