### ISSUE TITLE
Additional ENgage Analytics

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#42]
We'd like to review again the options we have for ENgage Analytics data.  We are being asked to find stats on:

1. Total Logins
2. Unique logins with name of member
3. Application Downloads
4. List of Members with Push Notification Set to ON
5. List of Members with Push Notification Set to Off
6. # of Logins in the first 31 days after download with Push Notifications ON
7. # of Logins in the first 31 days after download with Push Notifications OFF
8. # IS Push Notifications set to Members (Total)
9. # IS opened. 

I know we currently do some of this and maybe we do it all.  I am adding this ticket to spur our conversation about what we can and can't do.  Then we need an estimate.

**Comment by beck24** [comment]
1. available through google apps
2. available through google apps (10 this year) - Behavior > Events > User > Login
![screen shot 2018-01-30 at 4 06 41 pm](https://user-images.githubusercontent.com/738363/35598326-9c9403b4-05d7-11e8-899f-080a4e6036cc.png)

3. these are only available via apple and google.  I have access to them through the Arck account.
As of now:
Apple: only has per-month stats, on 8 active devices this month
Android: 67 lifetime installs, currently on 21 active devices

4-7: I don't think we know the status of their push notification settings.  Perhaps through onesignal we could see that?

8: Not sure what you're asking

9: available on the google analytics as sessions

Probably best to hop on a call to go through some of these together I would guess
