### ISSUE TITLE
Part 1: IS Change in ENsight  

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#45]
We would like to change the way people access Innovation Spotlights so that we can track their access.  

As we see it, this would include creating a new Tab on ENsight where we can post the Innovation Spotlights by Topic. The data for this page would be a series of pages in ENsight that each have a specific Innovation Spotlight on them with the member or thought leader contact info and photo.  See attached. 

The list of IS on the Innovation Spotlight tab would then flow into ENgage on the Innovation Spotlight menu item and replace the current system we have where the app links to a PDF.  

The reasoning behind this change includes needing the following: 
1. Sort Innovation Spotlights by Topics
2. Track access in both ENsight and ENgage
3. Secure content on ENsight instead of leaving it on the External Server

To do this, we will need a new Tab like the one attached and a new type of IS page that the links lead to.  

On the Innovation Spotlight Tab page, we will need to be able to:
1. Add/Edit Topic Headings 
2. Add new Innovation Spotlight Pages (see below and attached graphic) under each heading. 

To populate this page, we will need to add each IS as a separate page.  We will need to be able to: 
1.	Choose either a Thought Leader or a Member type page
2.	 Add 1 or 2 Member or Reference names and photos (preferably pulled from their Member and Reference Profile Pages. 
3.	Populate their contact info
4.	Assign Tags to IS Documents  and display them on the page
5.	Track when members access an IS Page and add tracking in MIRG to the Participation Menu.  Can we do this? 
6.	Add the recording (we can do this with Resources)

![ensight is page](https://user-images.githubusercontent.com/25776549/36454556-b265366c-1659-11e8-9c9a-8cceb4d08ff3.png)

<img width="510" alt="is layout" src="https://user-images.githubusercontent.com/25776549/36454580-d045ccaa-1659-11e8-9137-19c1de98e6ab.png">

The following are questions we have:
1.	Sometimes the IS is derived from a Webinar.  We need to consider what that might mean.  Is it as simple as the recording and resources are accessed on both pages but the IS Brief Overview only lives on the IS page and the webinar page has the description and the attendees?

**Comment by beck24** [comment]
To answer your question: It can be however we design it, but I think that's probably the simplest way.

I have some questions of my own:

1. Is there a functional difference between a "thought leader" and a "member" IS page?

1. Who can see these IS pages? Everyone?

1. Tracking - there's a few ways we can do this, but if we're doing the custom tracking in the app that we discussed it would be best to do them together and store the data in the same way, preferably in a separate flat table.  I guess the question is are we doing the custom analytics?

1. Topic headings - how should they be ordered?  In the screenshot there doesn't seem to be any logical order.  Not alphabetical or anything...

1. Experts - I see in the screenshot there are "expert" names below each topic.  That's not mentioned in the description.  What's the function and/or how do you see those being defined?

1. Who can create these IS pages?  Limited to admin?

**Comment by sang-entech** [comment]
Let me take a crack in answering your questions:

1. There's no functional difference other than its defined category.
2. Every member will have access and see these IS pages.
3. I discussed this in another ticket #51 but yes, the thought is that we would like to use flat table to capture the custom analytics.
4. Most likely it will be alphabetized (Nancy will confirm - might be listed in order they want seen.)
5. Nancy.. please answer this one. (I'm not sure how it'll be used - flat information vs link to their respective Experts page.)
6. YES.. very important. ONLY admins can create & edit these IS pages.

Thanks!

**Comment by ncadjan** [comment]
Answer to 4:  Currently, it has been a first-in first-listed sort of thing.  Let me ask if there is a reason to want to edit the order.  
Answer to 5: We have the Experts Menu option in ENgage.  I would like to have functionality to add experts and a link to their bios from this page.  Let's consider this Future Development as our last conversation with Karl de-emphasized this. 

Final: Matt do you ever sleep?

**Comment by beck24** [comment]
Sometimes, usually when I don't want to :)

**Comment by ncadjan** [comment]
Matt, a couple things came out of our conversation with the Leadership Team.  
1. Make the list of IS documents and headings alphabetical.  We can discuss how to do this based on how you are going to program the page. 
2. Hide the ENBlog tab for now. 
3. Make the Experts clickable to their profile (discuss how difficult this is to add--if it is costly, we will wait)

**Comment by beck24** [comment]
So you want to remove the blog functionality altogether (temporarily)?

**Comment by sang-entech** [comment]
Yes.. remove the blog functionality altogether - temporarily. It might be awhile before we re-introduce it or if at all.

**Comment by ncadjan** [comment]
Hide the tab.  If we want to go back to it, we’d like to have that option

Nancy Cadjan
Manager of Operations
Member Value Delivery
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[signature_1474970163]

**Comment by beck24** [comment]
ok, we can just disable those plugins then.  They can be re-enabled if you want it back

**Comment by ncadjan** [comment]
Thank you!

Nancy Cadjan
Manager of Operations
Member Value Delivery
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[signature_1952866470]

**Comment by beck24** [comment]
Can you send me the graphic with the tree?  Then I can use it directly, the uploaded image here is probably a bit too small for cropping it out

**Comment by ncadjan** [comment]
Its the one currently on EN Blog. 

Does that help?  I got it years ago.

**Comment by ncadjan** [comment]
How do I edit the topics if they are misspelled or I need to change the experts? When I click on the cog wheel, I can't edit it. 

How do we not show the Undecided Category? 

We need the member/Thought Leader name to appear because unlike the Profile, it doesn't show. It could be two places:  Under the title or on the Left.  I think it makes more sense to have it under the title because that looks more like an article. 

I added a photo for Carrie in the STEM article and it doesn't show:  http://ensight.arckdev.com/insights/view/2628493/td-bank-and-sun-life-financial-stem-talent-recruitment

If someone searches on a Topic, does it appear in the search?  And where?  we didn't think about this before, did we?

**Comment by beck24** [comment]
The edit link is fixed.

The uncategorized category is shown only to admin.  This is necessary because you could have spotlights added to a category, then you could delete that category, and the spotlight wouldn't be navigable from anywhere.  It's intended as a catch-all so that admin can re-categorize any that have fallen through the cracks.

We haven't discussed search, I'll have to add it to the indexes

**Comment by beck24** [comment]
Where/how did you add the photo?

**Comment by beck24** [comment]
One thing that has shown itself that also wasn't planned - it seems the audio/video embedding we use for resources doesn't work very well in mobile.  Images and documents are fine, but we put in some embedding stuff for A/V and none of my test mobile devices like it...

**Comment by ncadjan** [comment]
Photos are flowing from their member or reference profile.  If they are members, they should already have a profile (I added the pictures last night for the TD Bank employees).  I created a reference profile for the TL Erica Bank and added her picture. 

About the embedded content,  let me know what you see as a solution.  If it can't be imbedded and we can use the Resources below, we can do that.  Attaching a resource would be the way we would want to go when we secure the content on ENsight.  Right now, everything resides on your unsecured FTP site.

**Comment by beck24** [comment]
We didn't move the site data to the test server (there's just too much) so everyone has broken pictures unless you specifically upload a new one on the test server.

**Comment by ncadjan** [comment]
Yea, I uploaded the photos on Test.

**Comment by beck24** [comment]
ok, maybe I'm misunderstanding - where aren't you seeing the photos?  I just searched Erica Bank and found her profile with the picture.  I looked at the spotlights with her tagged and found her picture there

**Comment by ncadjan** [comment]
Click on the link above.  However, when I added the photo again just now,  it worked.  Click and see if it displays for you.  

We are going to need their names both at the top under the title and if there are two presenters, we need their names on the side associated with their photos so people know who is who.

**Comment by beck24** [comment]
Yep, that's already in the works.  Her photo showed for me before you re-uploaded it

**Comment by ncadjan** [comment]
Hmm.  It was missing when I went in there.

**Comment by ncadjan** [comment]
![is main page](https://user-images.githubusercontent.com/25776549/37541300-b80aede0-291f-11e8-8d0d-ef5f614617f9.png)

We need to format the Innovation Spotlight Tab and the IS Pages differently.  See attached. 

1. Display 3 most recent IS under each topic
2. Display Number total next to Heading
3. Make Heading clickable
4. Indent IS article headings
5. Make sure the colors are correctly alternating under each heading (which should not have any green shading behind it)

**Comment by ncadjan** [comment]
Here are our change requests
![is details page](https://user-images.githubusercontent.com/25776549/37541297-b3c1b368-291f-11e8-8ea6-e18a409c555c.png)
IS Page
1. Change the layout on the left for contact info--remove and make the picture/names a link to their profile.  
2. Increase size of Title and put authors below in smaller type
3. Can we add icons for the different types of resources? 
4. Put Tags only below the Member info on the left.

**Comment by beck24** [comment]
![screen shot 2018-03-19 at 9 53 21 am](https://user-images.githubusercontent.com/738363/37609852-691c4916-2b5b-11e8-9dfe-2cca9aff874d.png)

The different types of resources already have icon types

**Comment by ncadjan** [comment]
Changes to make:

1. MAIN IS TAB: Display only latest 3 insights (this was requested earlier)

2. SPECIFIC IS PAGE: Reduce the font size for the IS title.  Long titles look horrible. See http://ensight.arckdev.com/insights/view/2628615/driving-employee-performance-through-coaching-caring-behaviors-positive-emotional-experiences-and-meaningful-conversations

3. Increase font size for name under IS title.

4.  On Left, increase font size for Member/Thought Leader. 

5. Change layout for name, title, company so that there is no space between name and title, company
I prefer.. leave the spacing the way it is per person BUT just increase the size of name

6. Add space between two people when there are two presenters. With a divider line – light grey line - 75% width of column.  
 
QUESTION:  We may start to track the Experts in SF (they are currently manually created Profiles in ENsight).  If we add these people to SF with the same email address, will this sync to their existing ENsight Profiles or do we need to delete their existing manually-created profile and sync them over and change their Role to Expert? 

<img width="771" alt="screen shot 2018-03-22 at 2 55 18 pm" src="https://user-images.githubusercontent.com/25776549/37798714-2eed8784-2de3-11e8-84f6-c019b9783743.png">

**Comment by beck24** [comment]
As long as the emails match it should sync to their existing profiles - I don't know offhand what would happen with their role.  I assume it would be unchanged?  There's no provision in the import script for expert roles.  It would either stay the same or change to member, but I guessing it would stay the same.

**Comment by sang-entech** [comment]
Hi guys.. I think we need to bring Billy into this discussion because it's much more than that.

We never had contact status roles on Expert Panelists and Academic in Residence (was never addressed).. plus what type of membership records need to be created for them. Right now, we only have EN Staff which would give them full admin access (right)? So is it just "member" membership record? We need to figure out if Billy even has those 2 contact status roles being checked and synced.

Sang

**Comment by beck24** [comment]
Yeah, because I have no idea what you just said :)

**Comment by beck24** [comment]
Let's move this discussion to its own ticket so we're not hijacking this

**Comment by ncadjan** [comment]
Matt,  Someone just noticed that member company is not in the left area under their picture and title.  Can we quickly add that in ENsight today?  Just an oversight.  It is in the mockups above.
