### ISSUE TITLE
Part 2: IS Change in ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#46]
The page in ENgage would display links to the IS which would display in ENgage.  The Resources associated with the IS, including the recording could be launched from inside ENgage.  

On ENgage, we need (see attached for idea based on Profile Page): 
1.	Display the Thought Leader or Member Photo and Contact info
2.	Display the IS title and content
3.	Link to the recording  and make sure we can launch the recording. Currently, it opens in a browser but doesn't play. 
4.	Make sure the CSS works.  Currently there are issues with how numbered and bulleted lists in ENsight display in ENgage

Future Development: 
Add to or change the Home Page in ENgage so that Suggested Innovation Spotlights appear based on tags in the member profile. 
![engage is easy](https://user-images.githubusercontent.com/25776549/36454567-c0d898d8-1659-11e8-99d8-e1bfed1cbc0b.png)

![engage insights layout](https://user-images.githubusercontent.com/25776549/36454572-c9d791d2-1659-11e8-9bbd-1b3904363702.png)

**Comment by beck24** [comment]
For point 4 - can you screenshot me an example of where/how it's not working so I know where to look?

Also, Apple has announced that as of April (not sure of the exact day) all apps not supporting the iphone X display with the stupid notch will be rejected.  So we can push through with just these updates until then, but at some point in the very near future, if you want to release any new versions there's going to need to be a few hours invested in making it iphone X compatible specifically.

**Comment by ncadjan** [comment]
Here is an example.  I created a event page formatted like an IS.  Here is what we get.  This is also an issue (obviously) for Event Pages. 
![img_c27c64dcce45-1](https://user-images.githubusercontent.com/25776549/36486553-f1eae976-16db-11e8-9395-9caddd6d01bc.png)

**Comment by ncadjan** [comment]
I get this error when I click on the Insights Library in the Menu and then when I click OK, it is blank

![img_2405](https://user-images.githubusercontent.com/25776549/37369055-99d08f46-26cd-11e8-9e47-9c6da161d195.PNG)

![img_2406](https://user-images.githubusercontent.com/25776549/37369073-a34a3eaa-26cd-11e8-8f3e-336a33280e32.PNG)

**Comment by ncadjan** [comment]
![engage is details page](https://user-images.githubusercontent.com/25776549/37545960-6299a200-2930-11e8-84dc-dcc48b453038.png)

Layout Changes: 
1. Left justify the title and put on white bar (Android looks bolded but maybe not bold--see what you think)
2. Use the same font formatting as on the Member Profile Page for Name, title, company, location and network. 
3. Move "Thought Leader" or "Member to bottom of info and make it the right orange
3. Make the Member info clickable through to their Member Profile.  (Do we load Reference users?  I don't think so.  Most Thought Leaders will not have a click through)
4. If Tagged doesn't do any action, remove it.

**Comment by ncadjan** [comment]
![is ampersand](https://user-images.githubusercontent.com/25776549/37546332-f1efbac4-2931-11e8-8488-a353020c4ae4.PNG)
![engage andriod - is topics page - sang s thoughts](https://user-images.githubusercontent.com/25776549/37546335-f38985c2-2931-11e8-84d6-0ab929635d0c.png)


IS Topics Page and Category Page:
1. Add Major Header
2. Darken Grey and possibly increase row height
3. Bold Main Title
4. Indent Sub titles

**Comment by ncadjan** [comment]
IS Home Page: 
•	Remove the extra indent of Topic Categories (There should still be a slight indent as it was before--I know we are asking you to go back what I asked before)
•	How do we fix the ampersand issue across all pages? 
 
IS Topic Page:
•	How do we fix the ampersand issue across all pages? This issue still shows on “Change Management & Culture” Topic Page.
 
IS Details: 
•	Left Justify the title
•	Display Presenter info the same way it appears on the Profile (Name bolded/Larger font-line space-Title bolded-Company-Location) 
•	Make the name clickable to go to the Member Profile 
•	Darken the Orange about 20-30%


![img_0caed2585af2-1](https://user-images.githubusercontent.com/25776549/37799644-f0cc3060-2de5-11e8-8e8e-fbf3b7d7e94d.jpeg)

**Comment by beck24** [comment]
> How do we fix the ampersand issue across all pages?

It has to be embedded as trusted HTML which requires some special handling.  We have to identify where this will be an issue and I can do them all individually.

**Comment by ncadjan** [comment]
Can we not make the IS presenter name a click through to their profile?12

**Comment by beck24** [comment]
The presenter name _does_ click through the profile

**Comment by ncadjan** [comment]
Yep you are right
