### ISSUE TITLE
Footer Button Bar - Add New Button

### ISSUE THREAD

**Issue by sang-entech** [arckinteractive/en-issues#48]
## Footer Button Bar - Add New Button

Is there enough space to add 1 more button called "Agendas"?

![footer buttons bar](https://user-images.githubusercontent.com/35508395/36475716-886958d2-16c9-11e8-9232-0074b208d98b.png)
**Agendas** button will be a new name to **Events** menu.

**Events menu will broken up to 2 items: Agendas & Meeting Summaries. Will be discussed in another ticket.

**Comment by beck24** [comment]
Yeah I think there should be room

**Comment by sang-entech** [comment]
The button name will be "**Register**". Please suggest the most appropriate icon for this button as well.

Function:
IF upcoming "Network Meeting" (IN-NETWORK) is available, then go to that Network Meeting details.
IF upcoming "Network Meeting" (IN-NETWORK) isn't available yet (off-season), then go to "Agendas" page.

Please let me know if this function is available for Home buttons.

**Comment by beck24** [comment]
Note: specifically "Network Meeting"
