### ISSUE TITLE
Menu Changes

### ISSUE THREAD

**Issue by sang-entech** [arckinteractive/en-issues#49]
## Menu Changes
![menu listing proposed-3](https://user-images.githubusercontent.com/35508395/36475976-815fe6e0-16ca-11e8-96a2-54187e42a5de.png)

Events menu item is broken up into 2:
 - Agendas
 - Meeting Summaries

We would like to see the order of the menu (not shown) as:
1 - Home
2 - Search
3 - Insights Library
4 - Agendas (NEW)
5 - Meeting Summaries (NEW)
6 - My Network Topics
7 - My Connections
8 - Experts
9 - Settings
10 - Quick Tour
11 - App Info
12 - Sign Out 
(Order isn't approved yet, but we would like to shuffle them.)

**Comment by sang-entech** [comment]
NEW ORDER of menu:

1 - Home
2 - Insights Library
3 - Agendas (NEW)
4 - Meeting Summaries (NEW)
5 - My Network Topics
6 - My Connections
7 - Experts
8 - Networks
9 - Search
10 - Settings
11 - Quick Tour
12 - App Info
13 - Sign Out

For the 2 NEW menus.. I don't know what icons you guys are working with so please suggest the most appropriate one.

**Comment by beck24** [comment]
Agendas - upcoming
Meeting Summaries - past

**Comment by beck24** [comment]
Icon options:

http://ionicons.com/

https://fontawesome.com/v4.7.0/cheatsheet/

**Comment by paulstewart** [comment]
We have font-awesome-pro, too.
