### ISSUE TITLE
Events Page Changes

### ISSUE THREAD

**Issue by sang-entech** [arckinteractive/en-issues#50]
## Events Page - Broken up into Agendas & Meeting Summaries

**CURRENT**
Events Page with 2 Tabs (Upcoming & Past)

**PROPOSED**
Basically, we will be taking these tabs and make them their own pages (**Agendas** & **Meeting Summaries**) with no tabs. Functionality within the pages should remain the same.

![2 pages](https://user-images.githubusercontent.com/35508395/36476959-7e389a4a-16cd-11e8-9c2a-62be1504d566.png)

**Agendas** Page 
Filters:  Future Events;  IN-NETWORK only
Sort By:  Date of Events (Ascending)

**Meeting Summaries** Page
Filters:  Past Events;  IN-NETWORK only
Sort By:  Date of Events (Descending)

**Comment by ncadjan** [comment]
https://github.com/arckinteractive/en-issues/issues/54

Can we display meetings that a member has been invited to that are not in their network? We often have members invited to meetings other than their own. 2. What if members are members of two networks and have been invited to both?

**Comment by ncadjan** [comment]
There are layout issues with the Events Pages. Header graphic is not resized, Other graphics are all different sized and not aligned well.  No space between paragraphs, text doesn't wrap around photos and so forth. 

I understand that not all of this can be controlled but we need suggestions and ideas of how to make this page look better.  There are probably things we can do on the ENsight side and in our processes as well as some things in the app.  We just need a strategy.  
![graphics layout issues 1](https://user-images.githubusercontent.com/25776549/37547684-c4dae066-2938-11e8-856b-4a26a6caae48.PNG)


![graphic and layout issues 2](https://user-images.githubusercontent.com/25776549/37547692-d38163ec-2938-11e8-93d6-d659598580d5.PNG)

![graphic and layout issues 6](https://user-images.githubusercontent.com/25776549/37547702-dbe29f42-2938-11e8-9cb2-bc183886b82c.PNG)

**Comment by beck24** [comment]
> Can we display meetings that a member has been invited to that are not in their network?

Any events they are invited to are shown (that are tagged as network meetings) whether it's **their** network or not.

**Comment by beck24** [comment]
> can we standardize the stylesheets on the website and the app

Not really, it's not that simple.  We'll have to tackle things as they come up.
