### ISSUE TITLE
ENgage Statistics - NEW

### ISSUE THREAD

**Issue by sang-entech** [arckinteractive/en-issues#51]
## ENgage Transaction Log in ENsight
As discussed on our call with Matt & Billy couple of weeks ago, could we capture ENgage transaction log in ENsight. Exporting of these captured data into Excel will be required.

Some of the key data to capture:
1. Notification SET (On or Off)
    NEW DOWNLOAD or First time use should capture Notification SET = ON.
    (Please let us know if this is possible.)
2. Innovation Spotlight page loaded (each page & sub-page) & Resource link clicked action
3. Agendas page loaded (each page & sub-page)
4. Meeting Summaries page loaded (each page & sub-page)
5. Experts page loaded (each page & sub-page)
6. "Contact ND" button clicked action
7. New Download OR Upgrade to App capture would be nice.
(Preferably, it would be nice to capture all pages & sub-pages loading action.)

Fields required:
1. Member/Contact/User ID (not sure what identifier is being used now)
2. Member Name
3. Date & Time stamp
4. Page
5. Action (Loaded, Button Clicked, Link Clicked, Notification SET On or Off, etc)
6. App Version
Any other suggestions would be appreciated.

## Google Analytics - USER-ID feature
Since we only care about registered users, are we able to utilize USER-ID feature of Google Analytics? If we are able to tie our User ID with Google's User ID, would we be able to capture more accurate data than we have been? I would still like to use Google Analytics for capturing key user behavior & app performance. This is something we would like to explore more.

**Comment by beck24** [comment]
Currently notifications default to on, when you first install the app that's how it is

**Comment by beck24** [comment]
> New Download OR Upgrade to App capture would be nice.

I don't think this is possible

**Comment by sang-entech** [comment]
Fields required (EDITED):

 1.   Member/Contact/User ID (not sure what identifier is being used now)
 4.   Date & Time stamp
 5.   Page
 6.   Action (Loaded, Button Clicked, Link Clicked, Notification SET On or Off, etc)
7. Target 
 7.   App Version

**Comment by sang-entech** [comment]
Few questions:
1. What time zone is the logged date/time in? It appears to be either GMT or GMT-1.. is it possible to have it ET?

2. Resource/Link clicks are not being captured. Our most important stats are the consumption of these IS pages (already being captured) BUT, as important, are the consumption of the video file and PDF file links in the resource section. Currently, Nancy has them as links but I would like to see these resources in their own section (as it is in Agenda details) and with each click to these, it should be capture in our statistics.

3. You noted that this database might balloon out of control. Maybe, we should do an automatic monthly scrub and keep only the past 4 months? (I'll be downloading and backing up each month's worth of records.) What do you think?

4. Will Google Analytics - User-ID feature going to be turned ON and be applicable? I would like to capture few other statistics different from what we are capturing here.

Sang

**Comment by beck24** [comment]
1. It's logged in the timezone of the server which I believe is UTC.  I would recommend _not_ messing with timezones.  It only creates headaches.

2. Resource links are being captured, when they are added as resources.  If they are embedded as external links they cannot be tracked.  I can only track things that are generated by the app.  Embedded HTML is out of the scope of my event binding.  Nancy should be using the intended resources UI.

3. That sounds fine, do you want me to schedule that?

4. I already set that in the code, I don't know google analytics well enough to know if it's working or where that information goes.

**Comment by paulstewart** [comment]
@sang-entech Can you please give Matt and I (paul@arckinteractive.com and matt@arckinteractive.com) access to your Google Analytics accounts so we can verify tracking?

https://support.google.com/analytics/answer/1009702?hl=en

**Comment by beck24** [comment]
I have access to it, but I don't know how or where the user-id feature is supposed show up there.  I added it to the code as per the documentation, that's about all I can do with it

**Comment by sang-entech** [comment]
In reference to Matt's answers:

2. I tried both external links and Resource UI. I understand about the external links but it didn't capture the clicks on the resource UI items either. (This is as of last Thursday and Android.)

4. Google Analytics - User-ID. I assumed that we can't test that while on the test server, so I wanted to be sure that was addressed (enabled) and the issue was followed up upon. By any chance, is our GUID captured at all in this analytics or strictly Google's unique identifier?
(I emailed both of you our Google Analytics account info.)

**Comment by sang-entech** [comment]
I think it'll be best if you can schedule a scrub but to make sure to keep **4 months** worth so we can have overlap of data if not downloaded in time. I will have someone download that raw data (as full set) each month.

**Comment by beck24** [comment]
The resource UI click tracking is new, but it can't be done for embedded links.

Google analytics User ID - this is the case regardless of what API endpoint is being used.  It was actually added a long time ago.  I just don't know where to look on the google analytics dashboard to see if/how that data should be displayed.  I am not well versed in the usage of google analytics.

**Comment by sang-entech** [comment]
So I'm trying to test the ENgage statistics in ENsight admin>mobile statistics but it's either not logging right now or there's a lag in the system. Can you see if you can click on resource UI in ENgage and see if that's being captured? It wasn't for me last week.

**Comment by beck24** [comment]
No it's not, that feature is NEW and not deployed yet.  However, I'm letting you know that even with that feature, it won't be capturing embedded link clicks which Nancy appears to be using.

**Comment by sang-entech** [comment]
Understood.. Nancy didn't use the resource UI yet because she didn't want to spend the time and internet bandwidth (she actually has a cap). Let me know once that feature has been deployed and I'll upload various things using the resource UI to test.

Thanks

**Comment by beck24** [comment]
ok will do, though the resource UI doesn't incur any more bandwidth than anything else

**Comment by sang-entech** [comment]
lol.. I wanted to upload the actual webinar recordings and see if that will work on both statistics side and launching of the video file directly from the app. I was told we were still facing that hurdle.

**Comment by sang-entech** [comment]
2 questions about the stats:

1. What is "Networks" column used for?
2. App Version isn't showing up..

**Comment by beck24** [comment]
"Networks" column is for listing the networks the user belongs to, I believe it was requested earlier in the process.
App version works in the latest version
