### ISSUE TITLE
Part 3: ENgage Home Page--Suggested Innovation Spotlights and Meeting Agenda Add

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#54]
We would like to add two things to the ENgage Home Page that would appear before Suggested Member Connections

- **Meeting Agenda** (to parallel the Menu Item) to display the upcoming meeting information and the RSVP button (just like we do now from the menu).  If there is no upcoming meeting, remove display like we do when there is no Assistant. 
- **Three Suggested Innovation Spotlights** the same way we add Suggested Member Connections

This is an additional item.  Please bid for me. 

![engage home page meeting and suggested is](https://user-images.githubusercontent.com/25776549/36555902-9883f586-17c0-11e8-87ab-4fbc759aea15.png)

**Comment by beck24** [comment]
Meeting Agenda - specifically for 'network meeting'

**Comment by ncadjan** [comment]
Yes.  Always only for network meeting

Nancy Cadjan
Manager of Operations
Member Value Delivery
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[signature_908845036]

**Comment by beck24** [comment]
Questions on this one:

I just noticed that on the "Suggested Innovations Spotlights" there is the caret indicating it's a slider - is that intended?  If so what should the slider reveal?

Also it has "Areas of focus" and a link looking thing, I assume this corresponds to the topic of the spotlights.  Am I expected to show spotlights from just a single topic?   If so what?

What criteria is used to determine the "suggested" status of a spotlight?

**Comment by beck24** [comment]
For now I've just got it listing the 3 most recent spotlights

**Comment by ncadjan** [comment]
Sorry Matt.  I got slammed today.  I am going to go on a walk with my hubby and then come back and look at your comments.

We did put in one of the documents that we should be able to use tags to match up people and topics on the Home Page.  I thought the slider would be like the one for Suggested Member Connections where you could choose a different topic.

But let me look later

**Comment by ncadjan** [comment]
Our Suggested Member connection function works based on a member's Areas of Focus tags.  I thought we would use the same thing for the Innovation Spotlights.  We can tag the spotlights with the same tags as in the member profiles and then it would pull up spotlights related to those areas of focus.  

How do you see the best way to populate the suggested Innovation Spotlights? 

The one flaw in my way is what do we post if they do not have any tags in their profile? Can we default to the 3 most recent?

**Comment by ncadjan** [comment]
I got this error and then no suggested ISs.  Maybe that is because he doesn't have the right tags? 

![img_2404](https://user-images.githubusercontent.com/25776549/37369119-ce0ebaf8-26cd-11e8-877b-4e8ff4509278.PNG)


![img_2407](https://user-images.githubusercontent.com/25776549/37369130-d5b3549e-26cd-11e8-8811-266cd73955cd.PNG)

**Comment by beck24** [comment]
That's the problem with releasing a test-app before I'm done with changes on the server side :)

**Comment by ncadjan** [comment]
HA!

**Comment by ncadjan** [comment]
Just let me know when you are ready for me to check on things again.

**Comment by ncadjan** [comment]
Changes to Home Page
1. Check that all heading text is the same size.  Meeting Agenda and Suggested Innovation Spotlights looks different. 
2. Change the layout for the Meeting Agenda with a different stye RSVP button and wrap text for the titles.  
3. CONDITIONAL: Make the RSVP button, Agenda Button on the ribbon, and the Agenda on the Menu all  go to the Agenda page where we list all potential meetings UNLESS we can use the logic described below.
4. Innovation Spotlights:  How are we choosing which Spotlights show?  Can we use the Tags?  In this version they are not rotating. 
5. Can we add the slide so that we can see more IS (Button would say More Innovation)

NEW LOGIC: If meeting Count for user (upcoming & in-network/invited) > then go to Agendas Main Page. This is mainly for users with multiple networks or who are invited.  ELSE go to next Upcoming and IN-Network meeting (assumption that there will always be 1 active meeting--even a shell)

LOGIC QUESTIONS:  
1. Can we display meetings that a member has been invited to that are not in their network?  We often have members invited to meetings other than their own. 2. What if members are members of two networks and have been invited to both? 

![engage home](https://user-images.githubusercontent.com/25776549/37547348-bbd85cd4-2936-11e8-8436-3375fee0b627.png)

**Comment by beck24** [comment]
> In this version they are not rotating

What do you mean by that?

They're chosen by matching on profile tags.  The most recent spotlights that match a users profile tags.  If the user has no tags, it just does the most recent spotlights.

**Comment by beck24** [comment]
Otherwise done

**Comment by ncadjan** [comment]
ENgage Home Page
1. Add Date to the Agenda Section
2. Remove extra grey
3. Change the Ribbon name to Register (yes we know it's inconsistent but we are following orders)
4. How are the Suggested Innovation Spotlights selected to be displayed?  
5. How do the Suggested Innovation Spotlights rotate and how often? 

![img_52d88f85e1c9-1](https://user-images.githubusercontent.com/25776549/37799887-b90e98ba-2de6-11e8-8ebd-45d7f7705270.jpeg)

**Comment by beck24** [comment]
What do you mean by "Ribbon name to Register" - the RSVP button?

**Comment by beck24** [comment]
> How are the Suggested Innovation Spotlights selected to be displayed?
How do the Suggested Innovation Spotlights rotate and how often?

They are the most recent spotlights that match the user profile tags.  If the user has no tags, then it's just the most recent overall.
They don't "rotate" at all, they're just replaced when a newer spotlight matching the tags becomes available.

**Comment by beck24** [comment]
I can't put the date to the left, there's just not enough room on smaller phones.  I can put it just above and it works ok.

![screen shot 2018-03-23 at 11 45 21 am](https://user-images.githubusercontent.com/738363/37847935-bba9433c-2e8f-11e8-891c-edb03061d6f9.png)

**Comment by ncadjan** [comment]
Date looks good.
