### ISSUE TITLE
Quick Tour Needs to be Updated with new IS info and new Menu 

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#55]
Change Screen 1 to show the new menu
Change Screen 2 to display the new IS options.  Text can read "Access a list of Innovation Spotlights--business challenges, solutions and lessons from our members and selected thought leaders directly from your Home Page.  Then show the part of the Home Page with Suggested Innovation Spotlights. 
Add new Screen 3 to focus on Registration. 

![quick tour update 1](https://user-images.githubusercontent.com/25776549/37548214-eec16e56-293b-11e8-8d3e-d3627781e02a.jpeg)

![quick tour update 2](https://user-images.githubusercontent.com/25776549/37548217-f1878b66-293b-11e8-8b36-bfdf84d04ced.jpeg)

**Comment by ncadjan** [comment]
Page 2 needs a period at the end of the sentence. 

Page 5 needs to say "Select Agendas" 

The Tour ends on page 10 but the page guide at the bottom says there are 10 out of 11.  Are we missing a page? 

Issue with the Quick Tour: 
If I run the Quick Tour once an then go back to run it again, it shows a blank screen.  If I close the app, it is accessible again.  

This also happens if I get to the end of the Quick Tour and try to go back to the beginning using either a swipe or the arrows.  Go to the end, swipe back two screens and everything disappears.  

Back seems to work to get things back on track every time. 

Not a Show Stopper.  But can we fix?

**Comment by beck24** [comment]
This has all been updated in 1.8.6
I couldn't recreate your blank screen on the tour thing though.  Try the new version

**Comment by ncadjan** [comment]
Seems OK now.
