### ISSUE TITLE
Admin Report 

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#61]
We need a report that includes current data and some new fields.  This will require some changes to the profile data.    Please estimate the hours. 

[Data Points Needed.xlsx](https://github.com/arckinteractive/en-issues/files/1882368/Data.Points.Needed.xlsx)

**Comment by beck24** [comment]
I've taken a look at the report, some of that is certainly no problem.  There are a bunch of columns that I'm not familiar with (plus those that are denoted as new) - probably best if we could jump on a call some time next week and go over it so I can get a good idea of what data this is and where it's coming from.

**Comment by ncadjan** [comment]
I could not find the ticket again so I rewrote it.  Closing this one.
