### ISSUE TITLE
Adding the EN Tagline to ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#63]
TBD

**Comment by beck24** [comment]
Is there anything I need to know about this?  I'm not sure what it means by the title.

**Comment by ncadjan** [comment]
It’s a placeholder to remind me to ask you to update the logo on the startup screen to include the tagline we use.

Nancy Cadjan
Manager of Operations
Member Value Delivery
Executive Networks, Inc.

Direct: 1.415.399.9797 ext. 820
Mobile: 1.801.404.7564
ncadjan@executivenetworks.com<mailto:ncadjan@executivenetworks.com>
www.executivenetworks.com<http://www.executivenetworks.com/>
[signature_297374351]

**Comment by beck24** [comment]
ah ok

**Comment by ncadjan** [comment]
Not going to spend time/money  on this
