### ISSUE TITLE
BCC Welcome Letters to  membershipdesk@executivenetworks.com

### ISSUE THREAD

**Issue by paulstewart** [arckinteractive/en-issues#9]
"Please add BCC to the Welcome emails for membershipdesk@executivenetworks.com Ari can make sure the letters go through.  Or is there a location on ENsight where he can retrieve them? 

"

**Comment by beck24** [comment]
I can do either - bcc to be sent out by email OR keep a log that can be viewed on the site (or both, but that would be superfluous and more expensive).

**Comment by ncadjan** [comment]
BCC is good.  Ari wants to know it went out.  

BTW: We did some tests on a new member to PDN and the member got the Welcome Letter BUT the ND did not.  While you are in here, can you also CC the ND? (I thought we already had that function).

**Comment by beck24** [comment]
so, apparently the BCC function of sendgrid is broken in the version of the API we're using, but updating the API will take some time and require regression testing and stuff that we don't have time for at the moment.  So what I'm doing instead is sending the email to the user, then sending a separate copy of the email to the ND, with a CC to a global email that can be set in the settings.

**Comment by ncadjan** [comment]
Looks good.

**Comment by ncadjan** [comment]
We just tested on production with Ari as the BCC and then me as the BCC and neither of us received the email  Is there something you need to turn on on the production server to make this work?  

BTW:  I did set it in the Admin Page

**Comment by ncadjan** [comment]
<img width="981" alt="screen shot 2017-04-12 at 5 12 15 pm" src="https://cloud.githubusercontent.com/assets/25776549/24983267/356767be-1fa3-11e7-9807-da9e809211be.png">
